news/urls.py
from django.urls import include, path
from .views import categories, home, news_details, news_form
from .views import CategoryViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'categories', CategoryViewSet)

urlpatterns = [
    path("", home, name="home-page"),
    path("news/<int:id>", news_details, name='news-details-page'),
    path("categories", categories, name="categories-form"),
    path("news", news_form, name="news-form"),
    path("api/", include(router.urls)),
]

spotnews/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

news/models.py
from django.db import models
from news.utils import validate_title


class Category(models.Model):
    name = models.CharField(max_length=200, blank=False, null=False)

    def __str__(self) -> str:
        return self.name


class User(models.Model):
    name = models.CharField(max_length=200, blank=False, null=False)
    password = models.CharField(max_length=200, blank=False, null=False)
    role = models.CharField(max_length=200, blank=False, null=False)
    email = models.EmailField(max_length=200, blank=False, null=False)

    def __str__(self) -> str:
        return self.name


class News(models.Model):
    title = models.CharField(max_length=200, blank=False, null=False, validators=[validate_title]) # NOQA
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE) # NOQA
    created_at = models.DateField()
    image = models.ImageField(upload_to="img/", blank=True, null=True)
    categories = models.ManyToManyField("Category") # NOQA

    def __str__(self):
        return self.title

news/forms.py
from django import forms

from news.models import Category, User
from news.utils import validate_title


class CreateCategoryForm(forms.Form):
    name = forms.CharField(max_length=200, required=True)


class CreateNewsForm(forms.Form):
    title = forms.CharField(max_length=200, validators=[validate_title])
    content = forms.CharField(widget=forms.Textarea)
    author = forms.ModelChoiceField(queryset=User.objects.all())
    created_at = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    image = forms.ImageField(required=False)
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all())

news/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from news.forms import CreateCategoryForm, CreateNewsForm
from news.models import Category, News, User
from news.serializers import CategorySerializer
from rest_framework import viewsets


def home(request):
    context = {"news_list": News.objects.all()}
    return render(request, "home.html", context)


def news_details(request, id):
    news = get_object_or_404(News, id=id)
    categories = news.categories.all()
    return render(
        request, "news_details.html", {"news": news, "categories": categories}
    )


def categories(request):
    if request.method == "POST":
        form = CreateCategoryForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            Category.objects.create(name=name)
            return redirect("home-page")
    else:
        form = CreateCategoryForm()
        return render(request, "categories_form.html", {"form": form})


def news_form(request):
    if request.method == 'POST':
        form = CreateNewsForm(request.POST, request.FILES)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            news = News.objects.create(
                title=cleaned_data['title'],
                content=cleaned_data['content'],
                author=cleaned_data['author'],
                created_at=cleaned_data['created_at'],
                image=cleaned_data['image']
            )
            for category in cleaned_data['categories']:
                news.categories.add(category)
            return redirect('home-page')
        else:
            return HttpResponse("O formulário inválido", status=400)
    else:
        form = CreateNewsForm()
        users = User.objects.all()
        categories = Category.objects.all()
        return render(request, 'news_form.html', {
            'form': form,
            'users': users,
            'categories': categories
        })


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

news/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SpotNews{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="header">
        <ul class="header-links">
            <li><a href="{% url 'home-page' %}">Home</a></li>
            <li><a href="{% url 'categories-form' %}">Cadastrar Categorias</a></li>
            <li><a href="{% url 'news-form' %}">Cadastrar Notícias</a></li>
        </ul>
    </header>

    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

news/templates/categories_form.html
{% extends 'base.html' %}

{% block title %}Formulário para Nova Categoria{% endblock %}

{% block content %}
    <form method="post" action="{% url 'categories-form' %}">
      {% csrf_token %}
      <label for="id_name">Nome:</label>
      <input type="text" name="name" maxlength="200" required>
      <button type="submit">Salvar</button>
    </form>
{% endblock %}

news/templates/home.html
{% extends 'base.html' %}

{% block title %}Página Inicial{% endblock %}

{% block content %}
    <h1>Página Inicial</h1>

    {% for news_item in news_list %}
        <div class="news-item">
            <h2 class="news-title">{{ news_item.title }}</h2>
            <span class="news-date">{{ news_item.created_at|date:"d/m/Y" }}</span>
            <img src="/static{{ news_item.image.url }}" alt="{{ news_item.title }}">
        </div>
    {% endfor %}
{% endblock %}

news/templates/news_details.html
{% extends 'base.html' %}

{% block title %}Página de Detalhes da Notícia{% endblock %}

{% block content %}
    <div class="news-container">
        <h1 class="news-title">{{ news.title }}</h1>
        <p class="news-content">{{ news.content }}</p>
        {% if categories %}
            <span class="news-categories">
                <h2>Categorias</h2>
                <ul>
                    {% for category in categories %}
                        <li>{{ category.name }}</li>
                    {% endfor %}
                </ul>
            </span>
        {% endif %}
        <div class="news-details">
            <span class="news-author">{{ news.author }}</span>
            <img src="/static{{ news.image.url }}" alt="{{ news.title }}">
            <span class="news-date">{{ news.created_at|date:"d/m/Y" }}</span>
        </div>
    </div>
{% endblock %}

news/templates/news_form.html
{% extends 'base.html' %}

{% block title %}Formulário para Nova Notícia{% endblock %}

{% block content %}
<form method="post" action="{% url 'news-form' %}" enctype="multipart/form-data">
  {% csrf_token %}

  <label for="id_title">Título:
    {{ form.title }}
  </label>

  <label for="id_content">Conteúdo:
    {{ form.content }}
  </label>

  <label for="id_author">Autoria:
    <select id="id_author" name="author">
        {% for user in users %}
        <option value="{{ user.id }}">{{ user.username }}</option>
        {% endfor %}
        {% if value == selected%}
            <option value="{{ user.id }}" selected>{{ form.author }}</option>
        {% else %}
            <option value="{{ user.id }}">{{ user.username }}</option>
        {% endif %}
    </select>
</label>

  <label for="id_created_at">Criado em:
    {{form.created_at}}
  </label>

  <label for="id_image">URL da Imagem:</label>
  {{ form.image }}

  <label>Categorias:</label>
  {% for category in categories %}
  <label for="id_categories_{{ categories.id }}">{{ category.name }}</label>
  <input type="checkbox" name="categories" id="id_categories_{{ categories.id }}" value="{{ category.name }}">
  {% endfor %}

  <button type="submit">Salvar</button>
</form>
{% endblock %}